name: Generate and deploy slides

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install ford and ghp-import
      run: |
        python -m pip install ford
        python -m pip install ghp-import

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Generate documentation
      run: |
        ford heatcompact3d.md

    - name: Deploy slides to gh-pages
      run: |
        git config user.name "github-action"
        git config user.email "github-action"
        ghp-import -m "Update slides" --push --branch gh-pages doc
